// Code generated by go generate ./internal/i18n/; DO NOT EDIT.

package i18n

// Korean is the 한국어 catalog (auto-translated).
var Korean = Messages{
	Subtitle:               "설정 및 플러그인 기반 코딩 에이전트",
	WelcomeTitleFmt:        "%s에 오신 것을 환영합니다",
	NoConfigYet:            "아직 구성이 없습니다 — 설정해 봅시다.",
	StartingChatFmt:        "%s 시작 중…",
	SetKeyHint:             "API 키를 설정한 다음 `ok chat`을 실행하세요.",
	ConfigLabel:            "구성",
	ModelsLabel:            "모델",
	ConfigNotFound:         "찾을 수 없음 — 기본값 사용",
	ConfigErrorFmt:         "%s — 오류: %v",
	NoKey:                  "키 없음",
	Ready:                  "준비",
	GetStarted:             "시작하기",
	StepScaffold:           "ok.toml 스캐폴드",
	StepSetKey:             "API 키 설정",
	InitHint:               "프로젝트 메모리(AGENTS.md)는 세션 내에서 생성됩니다: `ok chat`을 실행한 다음 `/init`을 실행하세요 — 모델이 코드베이스를 분석하고 작성합니다. 구성은 `ok setup`을 사용하세요.",
	StepSetKeyHint:         "export DEEPSEEK_API_KEY=… 또는 .env에 추가",
	StepChatDesc:           "대화형 세션",
	StepRunDesc:            "일회성 작업",
	HelpFooter:             "ok 도움말 · 모든 명령",
	ChatTip:                "컨텍스트는 턴 간에 유지됩니다. 종료하려면 'exit' 또는 Ctrl-D를 입력하세요.",
	TurnCancelled:          "취소됨 — 프롬프트로 돌아가기",
	NoSessionToResume:      "저장된 세션이 없어 재개할 수 없습니다 — `ok chat`으로 새 세션을 시작하세요",
	ResumeRequiresTTY:      "--resume은 대화형 터미널이 필요합니다; 가장 최근 세션을 계속하려면 --continue를 사용하세요",
	PickSessionLabel:       "어떤 세션을 재개할까요?",
	ChatStatusThinkingFmt:  "%s 생각 중… (%ds · Esc 취소)",
	ChatStatusIdle:         "Tab 계획 전환 · Enter 전송 · Ctrl+F 검색 기록 · PgUp/PgDn 스크롤 · Ctrl-D 종료",
	ChatStatusPlanApproval: "Enter/y 승인 및 실행 · n/Esc 계획 유지 · PgUp/PgDn 스크롤",
	PlanApprovalPrompt:     "위에 계획 준비됨 — Enter/y로 승인 및 실행, n/Esc로 계속 계획",
	ChatStatusToolApproval: "y 한 번 승인 · a 이 세션 허용 · n 거부 · Ctrl-C 턴 취소",
	AskTypeSomething:       "다른 내용 입력",
	AskTypingHint:          "아래에 입력, Enter로 확인",
	AskChatInstead:         "없음 — 그냥 채팅",
	ChatStatusQuestion:     "↑/↓ 이동 · 번호 선택 · space 다중 선택 · Enter 확인 · ←/→ 전환 · Esc 취소",
	ToolApprovalPromptFmt:  "%s%s 허용? — [y] 한 번 · [a] 이 세션 · [n] 아니요",
	SlashCompactDone:       "세션 압축 완료 — 오래된 중간 부분이 요약으로 대체되었고, 최근 턴은 유지됨",
	SlashCompactFailed:     "압축 실패",
	SlashNewDone:           "새 세션 시작됨 — 이전 대화 내용 저장됨",
	SlashNewFailed:         "새 세션을 시작할 수 없습니다",
	SlashUnavailable:       "이 빌드에서는 명령을 사용할 수 없습니다",
	SlashUnknown:           "알 수 없는 명령",
	SlashTodoCleared:       "작업 목록 해제됨",
	SlashHelp:              "명령어: /audit · /search · /compact · /new · /todo · /model (모델 전환) · /mcp · /skill · /hooks · /memory · /help · 추가 스킬 (/init, /explore, …)",
	SlashPromptEmpty:       "MCP 프롬프트가 보낼 내용을 반환하지 않았습니다.",
	SlashMCPNone:           "MCP 서버가 구성되지 않았습니다. — ok.toml에 [[plugins]] 항목을 추가하세요.",
	CompHintSlash:          "↑/↓ 이동 · Tab/Enter 선택 · Esc 닫기",
	CompHintFile:           "↑/↓ 이동 · Tab/Enter 폴더 열기 또는 파일 선택 · Esc 닫기",
	CmdNew:                 "새 세션 포크",
	CmdCompact:             "컨텍스트 압축",
	CmdModel:               "모델 전환",
	CmdMemory:              "메모리 파일 보기",
	CmdMcp:                 "MCP 서버",
	CmdHooks:               "훅 관리",
	CmdSkill:               "스킬 관리",
	CmdAudit:               "감사 추적 확인",
	CmdSearch:              "기록 검색",
	CmdHelp:                "명령어 목록",
	CmdTodo:                "작업 목록 닫기",
	ArgSkillList:           "스킬 목록",
	ArgSkillShow:           "스킬 본문 보기",
	ArgSkillNew:            "새 스킬 스캐폴드",
	ArgSkillPaths:          "검색 경로 보기",
	ArgMcpAdd:              "서버 연결",
	ArgMcpRemove:           "서버 연결 해제",
	ArgMcpList:             "구성된 서버 표시",
	ArgMcpConnected:        "연결됨",
	ArgHooksTrust:          "이 프로젝트의 훅 신뢰",
	ArgHooksList:           "활성 훅 목록",
	ArgModelCurrent:        "현재",
	ListModelsHeaderFmt:    "모델 (활성: %s)",
	ListModelsHint:         "모델 전환기로 전환하거나 /model <provider/model> 입력",
	ListMemoryHeader:       "메모리 파일",
	ListMemoryNone:         "메모리: 없음 — \\\"#<노트>\\\"로 추가하거나 /init 실행하여 AGENTS.md 생성",
	ListSkillsHeaderFmt:    "스킬 (%d)",
	ListSkillsNone:         "스킬: 정의되지 않음 — /init 같은 내장 명령어 호출 또는 install_skill로 작성",
	ListHooksHeaderFmt:     "훅 (%d 활성)",
	ListHooksNone:          "훅: 활성화된 훅 없음 — .ok/settings.json (프로젝트, 신뢰 후) 또는 ~/.ok/settings.json (전역)에서 설정",
	ListMcpHeader:          "MCP 서버",
	ListMcpNone:            "MCP: 연결된 서버 없음 — ok.toml ([[plugins]]) 또는 프로젝트 .mcp.json에 추가",
	SelectProvidersLabel:   "활성화할 제공자 선택",
	EnterAPIKeysHeader:     "API 키 입력 (Enter 건너뛰기: 나중에 .env에서 설정):",
	MissingKeyIntro:        "ok.toml 준비 완료 — API 키만 있으면 됩니다.",
	WroteFileFmt:           "%s 작성됨",
	SetupComplete:          "설정 완료.",
	SetupCancelled:         "설정 취소됨.",
	TryHintFmt:             "시도: %s",
	NextHint:               "다음: API 키를 설정하세요 (export DEEPSEEK_API_KEY=... 또는 .env에 추가), 그런 다음 `ok run \\\"your task\\\"`를 실행하세요.",
	ConfirmReconfigureFmt:  "%s이(가) 이미 존재합니다. 재구성하고 덮어쓰시겠습니까?",
	KeepingExisting:        "기존 구성을 유지합니다.",
	NotOverwritingFmt:      "%s이(가) 이미 존재하므로 덮어쓰지 않습니다.",
	UnknownCommandFmt:      "알 수 없는 명령 %q",
	UsageRunHint:           "사용법: ok run [--model NAME] <task>",
	ErrorPrefix:            "오류:",
	WriteConfigErr:         "구성 쓰기 오류:",
	WriteEnvErr:            ".env 쓰기 오류:",
	SelectOneHint:          "(↑/↓ · Enter · q로 취소)",
	SelectManyHint:         "(↑/↓ · Space · Enter · q)",
	UsageBody: `ok — 설정 및 플러그인 기반 코딩 에이전트（다중 모델）

사용법：
  ok chat [--model 이름]                           대화형 세션（다중 턴）
  ok run  [--model 이름] [--max-steps N] <작업>    작업 실행 후 종료
  ok serve [--model 이름] [--addr 호스트:포트]     세션을 HTTP+SSE로 제공
  ok setup [경로]                                   대화형 설정 마법사
  ok mcp <add|remove|list>                         MCP 서버 관리
  ok update [--check]                               업데이트 확인 및 적용
  ok session <export|import|list>                   세션 내보내기/가져오기/목록
  ok doctor                                         환경 진단
  ok audit                                          실행 감사 추적 보기
  ok version                                        버전 표시
  ok help                                           도움말 표시
`,
}

func init() {
	registerResolver("ko", &Korean)
}
