// Code generated by go generate ./internal/i18n/; DO NOT EDIT.

package i18n

// Chinese is the 中文 catalog (auto-translated).
var Chinese = Messages{
	Subtitle:               "配置 + 插件驱动的编码代理",
	WelcomeTitleFmt:        "欢迎使用 %s",
	NoConfigYet:            "尚未找到配置 — 让我们来设置它。",
	StartingChatFmt:        "正在启动 %s…",
	SetKeyHint:             "设置您的 API 密钥，然后运行 `ok chat`。",
	ConfigLabel:            "配置",
	ModelsLabel:            "模型",
	ConfigNotFound:         "未找到 — 使用内置默认值",
	ConfigErrorFmt:         "%s — 错误：%v",
	NoKey:                  "无密钥",
	Ready:                  "就绪",
	GetStarted:             "开始使用",
	StepScaffold:           "搭建 ok.toml",
	StepSetKey:             "设置 API 密钥",
	InitHint:               "项目记忆（AGENTS.md）在会话中生成：运行 `ok chat`，然后 `/init` — 模型分析代码库并写入。配置请使用 `ok setup`。",
	StepSetKeyHint:         "export DEEPSEEK_API_KEY=… 或添加到 .env",
	StepChatDesc:           "交互式会话",
	StepRunDesc:            "一次性任务",
	HelpFooter:             "ok help · 所有命令",
	ChatTip:                "上下文在轮次之间保持。输入 'exit' 或 Ctrl-D 退出。",
	TurnCancelled:          "已取消 — 返回提示",
	NoSessionToResume:      "没有可恢复的会话 — 使用 `ok chat` 开始一个新会话",
	ResumeRequiresTTY:      "--resume 需要交互式终端；传递 --continue 以恢复最近的会话",
	PickSessionLabel:       "恢复哪个会话？",
	ChatStatusThinkingFmt:  "%s 思考中… (%ds · Esc 取消)",
	ChatStatusIdle:         "Tab 切换计划 · Enter 发送 · Ctrl+F 搜索历史 · PgUp/PgDn 滚动 · Ctrl-D 退出",
	ChatStatusPlanApproval: "Enter/y 批准并执行 · n/Esc 继续规划 · PgUp/PgDn 滚动",
	PlanApprovalPrompt:     "上方计划已就绪 — Enter/y 批准并执行，n/Esc 继续规划",
	ChatStatusToolApproval: "y 批准一次 · a 允许本次会话 · n 拒绝 · Ctrl-C 取消本轮",
	AskTypeSomething:       "输入其他内容",
	AskTypingHint:          "在下方输入，Enter 确认",
	AskChatInstead:         "无 — 仅聊天",
	ChatStatusQuestion:     "↑/↓ 移动 · 数字选择 · 空格多选 · Enter 确认 · ←/→ 切换 · Esc 取消",
	ToolApprovalPromptFmt:  "允许 %s%s？ — [y] 一次 · [a] 本次会话 · [n] 否",
	SlashCompactDone:       "会话已压缩 — 较早的中间部分被摘要替换，最近的轮次保留",
	SlashCompactFailed:     "压缩失败",
	SlashNewDone:           "新会话已开始 — 之前的对话记录已保存",
	SlashNewFailed:         "无法开始新会话",
	SlashUnavailable:       "此版本中命令不可用",
	SlashUnknown:           "未知命令",
	SlashTodoCleared:       "任务列表已清除",
	SlashHelp:              "命令：/audit · /search · /compact · /new · /todo · /model（切换模型）· /mcp · /skill · /hooks · /memory · /help · 以及技能（/init, /explore, …）",
	SlashPromptEmpty:       "MCP 提示未返回任何可发送的内容",
	SlashMCPNone:           "未配置 MCP 服务器 — 在 ok.toml 中添加 [[plugins]] 条目",
	CompHintSlash:          "↑/↓ 移动 · Tab/Enter 选择 · Esc 关闭",
	CompHintFile:           "↑/↓ 移动 · Tab/Enter 打开文件夹或选择文件 · Esc 关闭",
	CmdNew:                 "创建新会话",
	CmdCompact:             "压缩上下文",
	CmdModel:               "切换模型",
	CmdMemory:              "显示记忆文件",
	CmdMcp:                 "MCP 服务器",
	CmdHooks:               "管理钩子",
	CmdSkill:               "管理技能",
	CmdAudit:               "验证审计追踪",
	CmdSearch:              "搜索历史",
	CmdHelp:                "列出命令",
	CmdTodo:                "关闭任务列表",
	ArgSkillList:           "列出技能",
	ArgSkillShow:           "显示技能内容",
	ArgSkillNew:            "创建新技能",
	ArgSkillPaths:          "显示发现路径",
	ArgMcpAdd:              "连接服务器",
	ArgMcpRemove:           "断开服务器连接",
	ArgMcpList:             "显示已配置的服务器",
	ArgMcpConnected:        "已连接",
	ArgHooksTrust:          "信任此项目的钩子",
	ArgHooksList:           "列出活跃钩子",
	ArgModelCurrent:        "当前",
	ListModelsHeaderFmt:    "模型（活跃：%s）",
	ListModelsHint:         "使用模型切换器切换，或输入 /model <provider/model>",
	ListMemoryHeader:       "记忆文件",
	ListMemoryNone:         "记忆：无 — 使用“#<笔记>”添加，或运行 /init 生成 AGENTS.md",
	ListSkillsHeaderFmt:    "技能（%d）",
	ListSkillsNone:         "技能：未定义 — 调用内置命令如 /init，或使用 install_skill 创建",
	ListHooksHeaderFmt:     "钩子（%d 活跃）",
	ListHooksNone:          "钩子：无活跃 — 在 .ok/settings.json（项目，信任后）或 ~/.ok/settings.json（全局）中配置",
	ListMcpHeader:          "MCP 服务器",
	ListMcpNone:            "MCP：未连接服务器 — 在 ok.toml（[[plugins]]）或项目的 .mcp.json 中添加一个",
	SelectProvidersLabel:   "选择要启用的提供商",
	EnterAPIKeysHeader:     "输入 API 密钥（按 Enter 跳过，稍后在 .env 中设置）：",
	MissingKeyIntro:        "ok.toml 已就绪 — 只需一个 API 密钥。",
	WroteFileFmt:           "已写入 %s",
	SetupComplete:          "设置完成。",
	SetupCancelled:         "设置已取消。",
	TryHintFmt:             "试试：%s",
	NextHint:               "下一步：设置你的 API 密钥（export DEEPSEEK_API_KEY=... 或添加到 .env），然后运行 `ok run \\\"你的任务\\\"`。",
	ConfirmReconfigureFmt:  "%s 已存在。重新配置并覆盖？",
	KeepingExisting:        "保留现有配置。",
	NotOverwritingFmt:      "%s 已存在，不覆盖",
	UnknownCommandFmt:      "未知命令 %q",
	UsageRunHint:           "用法：ok run [--model 名称] <任务>",
	ErrorPrefix:            "错误：",
	WriteConfigErr:         "写入配置：",
	WriteEnvErr:            "写入 .env：",
	SelectOneHint:          "（↑/↓ · 回车 · q 取消）",
	SelectManyHint:         "（↑/↓ · 空格 · 回车 · q）",

	UsageBody: `ok — 配置和插件驱动的编码代理（多模型）

用法：
  ok chat [--model 名称]                          交互式会话（多轮）
  ok run  [--model 名称] [--max-steps N] <任务>   执行一次任务并退出
  ok serve [--model 名称] [--addr 主机:端口]      通过 HTTP+SSE 提供会话服务（浏览器客户端在 /）
  ok setup [路径]                                  交互式配置向导；写入 ok.toml（+ .env）
  ok mcp <add|remove|list>                        管理 ok.toml 中的 MCP 服务器
  ok update [--check]                              检查和应用更新
  ok session <export|import|list>                  导出/导入/列出会话
  ok doctor                                        完整环境诊断
  ok audit                                         查看执行审计追踪
  ok version                                       显示版本
  ok help                                          显示此帮助

示例：
  ok chat
  ok run "实现 main.go 中的 TODO"
  ok run --model mimo-pro "为此函数添加单元测试"
  echo "解释这段代码" | ok run

配置：
  解析顺序：标志 > ./ok.toml > ~/.config/ok/config.toml > 内置默认值
  密钥来自环境变量 api_key_env（例如 DEEPSEEK_API_KEY）。
  运行 'ok setup' 生成配置；查看 docs/SPEC.md。
`,
}

func init() {
	registerResolver("zh", &Chinese)
}
