// Code generated by go generate ./internal/i18n/; DO NOT EDIT.

package i18n

// Japanese is the 日本語 catalog (auto-translated).
var Japanese = Messages{
	Subtitle:               "設定とプラグイン駆動のコーディングエージェント",
	WelcomeTitleFmt:        "%sへようこそ",
	NoConfigYet:            "設定が見つかりません — セットアップしましょう。",
	StartingChatFmt:        "%sを開始中…",
	SetKeyHint:             "APIキーを設定してから `ok chat` を実行してください。",
	ConfigLabel:            "設定",
	ModelsLabel:            "モデル",
	ConfigNotFound:         "見つかりません — デフォルトを使用します",
	ConfigErrorFmt:         "%s — エラー: %v",
	NoKey:                  "キーがありません",
	Ready:                  "準備完了",
	GetStarted:             "はじめに",
	StepScaffold:           "ok.tomlをスキャフォールド",
	StepSetKey:             "APIキーを設定",
	InitHint:               "プロジェクトメモリ（AGENTS.md）はセッション内で生成されます: `ok chat` を実行し、`/init` を実行すると、モデルがコードベースを分析して書き込みます。設定には `ok setup` を使用してください。",
	StepSetKeyHint:         "export DEEPSEEK_API_KEY=… または .env に追加",
	StepChatDesc:           "インタラクティブセッション",
	StepRunDesc:            "ワンショットタスク",
	HelpFooter:             "ok help · すべてのコマンド",
	ChatTip:                "コンテキストはターン間で保持されます。'exit' または Ctrl-D で終了します。",
	TurnCancelled:          "キャンセルされました — プロンプトに戻ります",
	NoSessionToResume:      "復元する保存済みセッションがありません — `ok chat` で新しいセッションを開始してください",
	ResumeRequiresTTY:      "--resume はインタラクティブターミナルが必要です; 最新のセッションを続けるには --continue を指定してください",
	PickSessionLabel:       "どのセッションを復元しますか？",
	ChatStatusThinkingFmt:  "%s 考え中… (%ds · Esc でキャンセル)",
	ChatStatusIdle:         "Tab で計画切替 · Enter で送信 · Ctrl+F で履歴検索 · PgUp/PgDn でスクロール · Ctrl-D で終了",
	ChatStatusPlanApproval: "Enter/y で承認・実行 · n/Esc で計画継続 · PgUp/PgDn でスクロール",
	PlanApprovalPrompt:     "上記の計画準備完了 — Enter/y で承認・実行、n/Esc で計画継続",
	ChatStatusToolApproval: "y で1回承認 · a でこのセッション許可 · n で拒否 · Ctrl-C でターンキャンセル",
	AskTypeSomething:       "他の内容を入力",
	AskTypingHint:          "下に入力、Enter で確定",
	AskChatInstead:         "なし — チャットのみ",
	ChatStatusQuestion:     "↑/↓ で移動 · 数字で選択 · スペースで複数選択 · Enter で確定 · ←/→ で切替 · Esc でキャンセル",
	ToolApprovalPromptFmt:  "%s%s を許可しますか？ — [y] 1回のみ · [a] このセッション · [n] いいえ",
	SlashCompactDone:       "セッションを圧縮しました — 古い中間部分は要約に置き換え、最近のターンは保持",
	SlashCompactFailed:     "圧縮に失敗しました",
	SlashNewDone:           "新しいセッションを開始しました — 前のトランスクリプトは保存済み",
	SlashNewFailed:         "新しいセッションを開始できませんでした",
	SlashUnavailable:       "このビルドではコマンドは利用できません",
	SlashUnknown:           "不明なコマンド",
	SlashTodoCleared:       "タスクリストを消去しました",
	SlashHelp:              "コマンド: /audit · /search · /compact · /new · /todo · /model (モデル切替) · /mcp · /skill · /hooks · /memory · /help · スキル (/init, /explore, …)",
	SlashPromptEmpty:       "MCPプロンプトは送信するコンテンツを返しませんでした",
	SlashMCPNone:           "MCPサーバーが設定されていません — ok.tomlに[[plugins]]エントリを追加してください",
	CompHintSlash:          "↑/↓ 移動 · Tab/Enter 選択 · Esc 閉じる",
	CompHintFile:           "↑/↓ 移動 · Tab/Enter フォルダを開くかファイルを選択 · Esc 閉じる",
	CmdNew:                 "新しいセッションをフォーク",
	CmdCompact:             "コンテキストを圧縮",
	CmdModel:               "モデル切替",
	CmdMemory:              "メモリファイルを表示",
	CmdMcp:                 "MCPサーバー",
	CmdHooks:               "フック管理",
	CmdSkill:               "スキル管理",
	CmdAudit:               "監査証跡を確認",
	CmdSearch:              "履歴を検索",
	CmdHelp:                "コマンド一覧",
	CmdTodo:                "タスクリストを閉じる",
	ArgSkillList:           "スキルを一覧表示",
	ArgSkillShow:           "スキルの内容を表示",
	ArgSkillNew:            "新しいスキルをスキャフォールド",
	ArgSkillPaths:          "探索パスを表示",
	ArgMcpAdd:              "サーバーに接続",
	ArgMcpRemove:           "サーバーを切断する",
	ArgMcpList:             "設定済みサーバーを表示",
	ArgMcpConnected:        "接続済み",
	ArgHooksTrust:          "このプロジェクトのフックを信頼する",
	ArgHooksList:           "アクティブなフックを一覧表示",
	ArgModelCurrent:        "現在",
	ListModelsHeaderFmt:    "モデル (アクティブ: %s)",
	ListModelsHint:         "モデルスイッチャーで切り替えるか、/model <プロバイダー/モデル> と入力してください",
	ListMemoryHeader:       "メモリファイル",
	ListMemoryNone:         "メモリ: なし — 「#<メモ>」で追加するか、/init を実行して AGENTS.md を生成してください",
	ListSkillsHeaderFmt:    "スキル (%d)",
	ListSkillsNone:         "スキル: 定義なし — /init のような組み込みスキルを呼び出すか、install_skill で作成してください",
	ListHooksHeaderFmt:     "フック (%d アクティブ)",
	ListHooksNone:          "フック: アクティブなし — .ok/settings.json (プロジェクト、信頼後) または ~/.ok/settings.json (グローバル) で設定してください",
	ListMcpHeader:          "MCP サーバー",
	ListMcpNone:            "MCP: 接続されたサーバーはありません — ok.toml ([[plugins]]) またはプロジェクトの .mcp.json に追加してください",
	SelectProvidersLabel:   "有効にするプロバイダーを選択",
	EnterAPIKeysHeader:     "API キーを入力 (Enter でスキップし、後で .env に設定):",
	MissingKeyIntro:        "ok.toml の準備ができました — API キーを設定するだけです。",
	WroteFileFmt:           "%s を書き込みました",
	SetupComplete:          "セットアップが完了しました。",
	SetupCancelled:         "セットアップがキャンセルされました。",
	TryHintFmt:             "試す: %s",
	NextHint:               "次: APIキーを設定してください（export DEEPSEEK_API_KEY=... または .envに追加）、その後 `ok run \\\"あなたのタスク\\\"` を実行してください。",
	ConfirmReconfigureFmt:  "%s は既に存在します。再設定して上書きしますか？",
	KeepingExisting:        "既存の設定を保持します。",
	NotOverwritingFmt:      "%s は既に存在します。上書きしません。",
	UnknownCommandFmt:      "不明なコマンド %q",
	UsageRunHint:           "使用方法: ok run [--model NAME] <タスク>",
	ErrorPrefix:            "エラー:",
	WriteConfigErr:         "設定の書き込み:",
	WriteEnvErr:            ".envの書き込み:",
	SelectOneHint:          "(↑/↓ · Enter · q でキャンセル)",
	SelectManyHint:         "(↑/↓ · Space · Enter · q)",
	UsageBody: `ok — 設定とプラグイン駆動のコーディングエージェント（マルチモデル）

使い方：
  ok chat [--model 名前]                          インタラクティブセッション（マルチターン）
  ok run  [--model 名前] [--max-steps N] <タスク>  タスクを実行して終了
  ok serve [--model 名前] [--addr ホスト:ポート]    セッションをHTTP+SSEで提供（ブラウザクライアントは /）
  ok setup [パス]                                   対話型設定ウィザード
  ok mcp <add|remove|list>                         MCPサーバー管理
  ok update [--check]                               アップデートの確認と適用
  ok session <export|import|list>                   セッションのエクスポート/インポート/一覧
  ok doctor                                         環境診断
  ok audit                                          実行監査証跡の表示
  ok version                                        バージョン表示
  ok help                                           ヘルプ表示
`,
}

func init() {
	registerResolver("ja", &Japanese)
}
