package builtin

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/NB-Agent/ok/internal/tool"
)

func init() { tool.RegisterBuiltin(makeTool{}) }

// makeTool generates a complete Go builtin tool source file from a specification.
// After writing the file, the user must recompile (go build) to activate it.
// This is the agent's self-evolution engine — it can create new capabilities
// at runtime without manual scaffolding.
type makeTool struct{}

func (makeTool) Name() string { return "make-tool" }

func (makeTool) Description() string {
	return "Create a new built-in tool from a Go source file. Provide name, description, JSON schema, and Execute logic. Written to internal/tool/builtin/; available after rebuild."
}

func (makeTool) Schema() json.RawMessage {
	return json.RawMessage(`{"properties":{"executeGo":{"type":"string"},"name":{"type":"string"},"params":{"type":"string"},"readOnly":{"type":"boolean"}},"required":["name","description","executeGo"],"type":"object"}`)
}

func (makeTool) ReadOnly() bool { return false }

func (makeTool) Execute(ctx context.Context, args json.RawMessage) (string, error) {
	var p struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		Params      string `json:"params"`
		ExecuteGo   string `json:"executeGo"`
		ReadOnly    bool   `json:"readOnly"`
	}
	if err := json.Unmarshal(args, &p); err != nil {
		return "", fmt.Errorf("invalid args: %w", err)
	}

	name := p.Name
	if name == "" {
		return "", fmt.Errorf("name is required")
	}
	// Derive Go identifier from kebab-case name
	goName := kebabToCamel(name)
	fileName := name + ".go"

	// Default params schema
	if p.Params == "" || p.Params == "null" {
		p.Params = `{"type":"object"}`
	}

	readOnlyStr := "false"
	if p.ReadOnly {
		readOnlyStr = "true"
	}

	source := fmt.Sprintf(`package builtin

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/NB-Agent/ok/internal/tool"
)

func init() { tool.RegisterBuiltin(%s{}) }

// %s implements %s — generated by make-tool.
type %s struct{}

func (%s) Name() string { return %q }

func (%s) Description() string {
	return %q
}

func (%s) Schema() json.RawMessage {
	return json.RawMessage(%q)
}

func (%s) ReadOnly() bool { return %s }

func (%s) Execute(ctx context.Context, args json.RawMessage) (string, error) {
%s
}
`,
		goName,       // init call
		goName,       // struct name
		name,         // doc
		goName,       // type
		goName, name, // Name()
		goName, p.Description, // Description()
		goName, p.Params, // Schema()
		goName, readOnlyStr, // ReadOnly()
		goName, p.ExecuteGo, // Execute
	)

	// Write to internal/tool/builtin/
	dir := filepath.Join("internal", "tool", "builtin")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", dir, err)
	}
	targetPath := filepath.Join(dir, fileName)
	if err := os.WriteFile(targetPath, []byte(source), 0644); err != nil {
		return "", fmt.Errorf("write %s: %w", targetPath, err)
	}

	var b strings.Builder
	b.WriteString("# Tool Created\n\n")
	b.WriteString(fmt.Sprintf("- Name: `%s`\n", name))
	b.WriteString(fmt.Sprintf("- File: `%s`\n", targetPath))
	b.WriteString(fmt.Sprintf("- ReadOnly: %s\n", readOnlyStr))
	b.WriteString(fmt.Sprintf("- Lines: %d\n", len(strings.Split(source, "\n"))))
	b.WriteString("\n## Next Step\n")
	b.WriteString("Run `go build ./...` to compile and activate the new tool.\n")
	b.WriteString("Run `go vet ./internal/tool/builtin/...` to check for syntax errors.\n")

	return b.String(), nil
}

// kebabToCamel converts "my-analyzer" to "myAnalyzer".
func kebabToCamel(s string) string {
	parts := strings.Split(s, "-")
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			result += strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return result
}
